### ISSUE TITLE
screen size

### ISSUE THREAD

**Issue by GeeGee23-Cat** [Writer-Sonic/Ai-Writer-#9]
I have just updated your app. On my Mac it is so huge it overfills the screen. I prefer to have the ability to adjust the size of the page
have the ability to minimise or enlarge the screen or to tile the windows to the left or right.  I can not find the ability to do this.
I can no longer see the green circle at the top of the screen to enter fullscreen mode.
attached photo 
![tempImageyEkXXN](https://github.com/user-attachments/assets/dcf096c3-4d3b-4673-9160-751e9bc4b70f)

**Comment by aryan1107** [comment]
Can you try minimizing? I am not sure why default was too big as I see on your screen, Ill try to release a new update but meanwhile can you try like I showed in the video here?
 
https://github.com/user-attachments/assets/d4375844-a7bf-4f88-8801-238555a435d9

**Comment by GeeGee23-Cat** [comment]
Hi
I tried that but as I cannot see the 4 edges of the screen there is nowhere
I can grab to minimize the screen size. Also I am unable to see the red
green and yellow circles on the top left of the screen. Due to me not being
able to see the edges of tour screen

BW
Heather

Heather Sent from Gmail Mobile

**Comment by aryan1107** [comment]
Hi, a new update has been approved by Apple. I tried to address the issue in this update. Could you please try updating using this link: https://apps.apple.com/in/app/ai-writer-generative-ai-chat/id6444013958

After updating, can you confirm if the issue is resolved? Also, could you let me know what Mac device you're using? This information would be helpful for future reference.

**Comment by GeeGee23-Cat** [comment]
Hi
Thanks for your quick response
Your fix is working fine.
I have a MacBook Air
macOS Sonoma version 14.5

BW
H
Heather Rowell
07798801336
14 Hanover Court
Burleigh Mews
Caversham
RG4 6QR
